name: 'InfluxDB 3 Core Action'
description: 'Install and configure InfluxDB 3 Core.'
author: 'Thulasiraj Komminar'

branding:
  icon: 'database'
  color: 'purple'

inputs:
  influxdb3_database:
    description: "The initial database of the InfluxDB3 instance."
    required: false
    default: "default"

  influxdb3_create_token:
    description: "Whether to create an auth token."
    required: false
    default: "false"

outputs:
  influxdb3-auth-token:
    description: 'The token for InfluxDB3 authentication'
    value: ${{ steps.install-influxdb3.outputs.influxdb3-auth-token }}

runs:
  using: "composite"
  steps:
    - name: Download and Install InfluxDB3
      id: install-influxdb3
      shell: bash
      run: |
        export INFLUXDB3_DATABASE=${{inputs.influxdb3_database}}
        export INFLUXDB3_CREATE_TOKEN=${{inputs.influxdb3_create_token}}
        ${{ github.action_path }}/influxdb3-install.sh
